version: '3'

services:
  userland-app:
    container_name: userland
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    depends_on:
      - userland-db
      - userland-redis-server
      - broker
    networks:
      - net

  userland-db:
    image: postgres:10-alpine
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    env_file: .env
    networks:
      - net

  userland-admin:
    image: adminer
    restart: always
    networks:
      - net
    depends_on:
      - userland-db
    ports:
      - "8090:8080"

  userland-redis-server:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - net
    env_file: .env
    volumes:
      - redis_data:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: zookeeper
    env_file: .env_kafka
    networks:
      - net

  broker:
    image: confluentinc/cp-kafka:6.2.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    env_file: .env_kafka
    networks:
      - net

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8010:8080"
    depends_on:
      - zookeeper
      - broker
    restart: always
    env_file: .env_kafka
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  redis_data:
  db_data: